services:
  mongodb:
    image: mongo:8
    volumes:
      - mongo:/data/db
    container_name: reservou_mongodb
    environment:
      MONGO_INITDB_DATABASE: attachments
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - "27017:27017"
    command: "--bind_ip_all --quiet --logpath /dev/null --replSet rs0"
  mongo-init:
    container_name: reservou_mongodb_init
    image: mongo:8
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval
      '
      rs.initiate( {
         _id : "rs0",
         members: [
            { _id: 0, host: "localhost:27017" }
         ]
      })
      '
  redis:
    image: redis:latest
    container_name: reservou_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
volumes:
  mongo:
  redis_data: